name : Simple Calculator CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Set up Python 3.11
      uses: actions/setup-python@v6
      with:
        python-version: 3.13

    - name: Install dependencies
      run: 
        pip install -r requirements.txt

    - name: Run tests with coverage
      run:
        pytest --cov=library_service --cov-report=xml tests/

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
    